config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'

  get '/search', to: 'stores#search', as: 'search'

  resources :stores, only: [:index, :show]
  resources :tests, only: [:new]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :tests, only: [:create]
    end
  end
end

app/models/search_location.rb
class SearchLocation < ActiveRecord::Base
  def self.find_using(name)
    capitalized_name = name.split(" ").collect(&:capitalize).join(" ")
    where(:name => (capitalized_name + " New York")).first
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :tests
  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?
  fuzzily_searchable :name

  private
    def full_address
      "#{address} #{city} #{state_code} #{postal_code}"
    end
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :store

  validates_presence_of :download, :upload, :latency #=> Add store to this list
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/controllers/api/v1/tests_controller.rb
class Api::V1::TestsController < ApiController
  def create
  end

  def new
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_cache_buster

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def search
    @stores = SearchService.new(store_params).execute
    if @stores == nil
      flash[:notice] = "Both fields can not be blank!"
      redirect_to root_path
    end
  end

  def index
  end

  def show
    @store = Store.find(params[:id])
    @current_ip = self.request.remote_ip
    @distance = @store.distance_to(@current_ip)
  end

  private

  def store_params
    params.require(:store).permit(:name, :location)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
  def within_proximity
    @distance <= 1
  end
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CafeLatency</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/backbone.marionette/2.4.1/backbone.marionette.min.js' %>
  <%= javascript_include_tag 'application' %>
  <script src="//speedof.me/api/api.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
<% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/stores/index.slim
= form_for(:store, method: :get, url: {action: "search"}) do |f|
  p Search
  = f.label :name
  = f.text_field :name, placeholder: 'Search for a cafe'
  br/
  = f.label :location
  = f.text_field :location, placeholder: 'Search for a location'
  = f.submit 'Search'
end

app/views/stores/search.slim
- @stores.each do |store|
  = link_to store_path(store) do
    p = store.name
    p = store.address
    br
  end
end

app/views/stores/show.slim
h1
  a[href==@store.url]
    =@store.name
h2 Yelp Rating
.rating
  p=@store.rating
h3 Address
.address
  p=@store.address
  p
    =@store.city
    | ,
    =<>@store.state_code
    =@store.postal_code

h3 Current IP:  
= @current_ip

h3 Distance:
= @distance

- if within_proximity
    h2 SpeedOf.Me API Consumer - Sample Page</h2>
    button id="btnStart" type="button" onclick="btnStartClick()"Start Test
    div id="msg"